version: '3.4'

services:

  marketplacedb:
    container_name: marketplacedb
    environment:
        SA_PASSWORD: "Admin1234"
        ACCEPT_EULA: "Y"
    restart: always
    ports:
      - "1433:1433"

  marketplace.admin.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - "ConnectionStrings:DefaultConnection=Server=marketplacedb;Database=MarketplaceDb;User Id=sa;Password=Admin1234;TrustServerCertificate=True"
    depends_on:
      - marketplacedb
    ports:
      - "8001:80"
